### ISSUE TITLE
create new login page

### ISSUE THREAD

**Issue by imeetsanghvi** [CANIS-NAU/ARORA-App#7]
**sub tasks:**
1. get new assets from _Shelby B._
2. see the Figma board for the UI created by _Darius_
3. the key board bug should be removed
4. Sign up and login page should look like this 
![image](https://user-images.githubusercontent.com/42674965/117217453-3fbdf980-adb6-11eb-8f1b-ec4314c75fc7.png)
add some icons that depict a login or signup page 
5. opening the app would directly take the user login page (which would display a small button in the corner to create new account)

**Comment by DariusDumel** [comment]
# Changes to step 4

Currently changing the whole design of the app is not necessary. Doing step 4 above is not necessary and the login page should look like this:

![image](https://user-images.githubusercontent.com/25535561/117221260-bd393800-adbd-11eb-9e56-c0520e9c1164.png)

**Comment by imeetsanghvi** [comment]
updates: 
1. updated the login page with few design changes
2. removed the keyboard bug
3. unified UI by using styles and reusing code, removed extra lines of code
![image](https://user-images.githubusercontent.com/42674965/117375992-15873d00-ae85-11eb-869c-05d4a0c73508.png)
![image](https://user-images.githubusercontent.com/42674965/117376003-19b35a80-ae85-11eb-881a-e68b23c4e67e.png)
