### ISSUE TITLE
implement new navigation

### ISSUE THREAD

**Issue by DariusDumel** [CANIS-NAU/ARORA-App#9]
meet wants to implement a new menu navigation based off a fab (floating action button).

**Comment by imeetsanghvi** [comment]
we stuck to a bottom navigation menu 
it has been implemented and is being tested today (on 4th June) if everything works well, we will merge all changes and bring it into the main.

https://asu.zoom.us/rec/share/8zu0TJlbdzSfr4W4cwx5Ize_2kYuPEWxRjmyoUwBbd61-eKJdL_LlvwSP_atESsc.6Od6EvUJJT5GG5tQ?startTime=1622843664000

walkthrough available here

Images here - https://nau-siccs-canis-lab.slack.com/archives/C01A8PVPL0L/p1622844508034100
